# Generated by Django 5.1.6 on 2025-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_rename_profile_profileapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileapp',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profileapp',
            name='profile_photo',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
